### PR TITLE
Bug fix for #1

### PR DESCRIPTION
**Pull request by marohrdanz**
This pull request is primarily a bug fix for #1. 

In addition, there is a commit that removes the now-superfluous lasso-canvas (to simplify code), and another commit to add some better comments in canvasDraw.js.

### CODE REVIEW

**Comment by marohrdanz** [comment]
In the context of an NG-CHM plugin, we are guaranteed unique values for 'text', because the 'text' field is the row or column label from the NG-CHM. (I verified that the NG-CHM builder insists on unique values for both the column and row labels).

If the data does not come from an NG-CHM, there is no such guarantee. I will brainstorm ideas for how to make this work in a non-NG-CHM setting. Although, maybe we should insist on the 'text' field being unique in general? So that we have some unique way to specify each of the defined data points? If we do that, it's enough to just have `sp.text == p.text` in that filter function.

**Comment by bmbroom** [comment]
Yes:

Although, maybe we should insist on the 'text' field being unique in general? So that we have some unique way to specify each of the defined data points? If we do that, it's enough to just have sp.text == p.text in that filter function.

**Comment by bmbroom** [comment]
Looks good to me.

I cannot see where I can leave a "review/approve" the request, but please go ahead.

**Review by bmbroom — APPROVED** [review]
Now I found it!

**Pull request merged**
